# В теории cassandra порты можно и не открывать
version: '3.8'

services:
  
  # Проверить порты внешние порты для драйвера. 40001 != порт для драйвера
  1.game-shop.cassandra:
    image: cassandra:5.0
    container_name: 1.game-shop.cassandra
    ports:
      - 9042:9042
    volumes:
      - ./data/cassandra-1:/data/db
    environment:
      - CASSANDRA_SEEDS=1.game-shop.cassandra,2.game-shop.cassandra,3.game-shop.cassandra
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  2.game-shop.cassandra:
    image: cassandra:5.0
    container_name: 2.game-shop.cassandra
    ports:
      - 40002:40002
    volumes:
      - ./data/cassandra-2:/data/db
    environment:
      - CASSANDRA_SEEDS=1.game-shop.cassandra,2.game-shop.cassandra,3.game-shop.cassandra
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  3.game-shop.cassandra:
    image: cassandra:5.0
    container_name: 3.game-shop.cassandra
    ports:
      - 40003:40003
    volumes:
      - ./data/cassandra-3:/data/db
    environment:
      - CASSANDRA_SEEDS=1.game-shop.cassandra,2.game-shop.cassandra,3.game-shop.cassandra
    networks:
      - cassandra-network
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  1.cassandra-client:
    image: cassandra-client:0.0.1
    container_name: 1.cassandra-client
    ports:
      - 40004:8080
    environment:
      - CASSANDRA_NODE_ADDRESS=1.game-shop.cassandra
      - CASSANDRA_NODE_PORT=9042
    depends_on:
      2.game-shop.cassandra:
        condition: service_healthy
    networks:
      - cassandra-network

networks:
  cassandra-network:
    driver: bridge